default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: 5
  host: <%= ENV['MYSQL_HOST'] || 'db' %>
  username: <%= ENV['MYSQL_USERNAME'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || 'password' %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: share-moments_development

test:
  <<: *default
  database: share-moments_test
